baseURL: https://damonmyers.com/
languageCode: en-us
title: logdamon

params:
  author: Damon Myers
  description: The blog of Damon Myers
  showToc: true

markup:
  highlight:
    style: emacs

social:
  github: https://github.com/damon-myers
  twitter: https://twitter.com/myersdamon

permalinks:
  posts: /:year/:month/:day/:title

module:
  imports:
    path: github.com/nodejh/hugo-theme-mini